name: Lensy-build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_27.0.app/Contents/Developer

      - name: Build Lensy
        run: |
          xcodebuild \
            -project Lensy.xcodeproj \
            -scheme Lensy \
            -configuration Debug \
            -sdk macosx \
            build

      - name: Test Lensy
        run: |
          xcodebuild \
            -project Lensy.xcodeproj \
            -scheme Lensy \
            -destination 'platform=macOS' \
            test
